name: Production-CI-CD

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  CONTAINER_NAME: demo
  S3_BUCKET_NAME: pulumidemobucket1
  S3_CODE_PATH: pulumi-code
  CODE_PATH: "./pulumi-code"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ env.CONTAINER_NAME }} ./Svelete-skeleton
          docker tag ${{ env.CONTAINER_NAME }}:latest ${{ env.ECR_REGISTRY }}/${{ env.CONTAINER_NAME }}:latest
          docker push ${{ env.ECR_REGISTRY }}/${{ env.CONTAINER_NAME }}:latest

      # - name: Download files from S3
      #   run: aws s3 cp s3://${{env.S3_BUCKET_NAME}}/${{env.S3_CODE_PATH}}/ . --recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 16.0.0

      - run: cd pulumi-code && npm install
      - uses: pulumi/actions@v4
        with:
          work-dir: ./pulumi-code
          refresh: true
          command: up
          stack-name: "priyankakale27/pulumi-eks/prod"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
